package com.proquest.mtg.dismetadataservice.csv;


public class CSVHeaders {
	public static final String kPubNumber = "PUB NUMBER";
	public static final String kVolumeIssue = "VOLUME ISSUE";
	public static final String kAdvisors = "ADVISORS";
	public static final String kIsbn = "ISBN";
	public static final String kPageNumber = "PAGE NUMBER";
	public static final String kPageCount = "PAGE COUNT";
	public static final String kPublisher = "PUBLISHER";
	public static final String kReferenceLocation = "REFERENCE";
	public static final String kBritishLibraryNumber = "BL NUMBER";
	public static final String kPqOpenUrl = "PQ OPEN URL";
	public static final String kExternalUrl = "EXTERNAL URL";
	public static final String kDissLangDesc = "DISS LANGUAGE DESCRIPTION";
	public static final String kDissLangCode = "DISS LANGUAGE CODE";
	public static final String kSchoolCode = "SCHOOL CODE";
	public static final String kSchoolName = "SCHOOL NAME";
	public static final String kSchoolCountry = "SCHOOL COUNTRY";
	public static final String kSchoolState = "SCHOOL STATE";
	public static final String kTitle = "TITLE";
	public static final String kEnglishTranslationOfTitle = "ENGLISH TITLE";
	public static final String kVariantTitle = "VARIANT TITLE";
	public static final String kAuthors = "AUTHORS";
	public static final String kDegreeCode = "DEGREE CODE";
	public static final String kDegreeDesc = "DEGREE DESC";
	public static final String kDegreeYear = "DEGREE YEAR";
	public static final String kAbstract = "ABSTRACT";
	public static final String kSubjectDesc = "SUBJ DESC";
	public static final String kSubjectCode = "SUBJ CODE";
	public static final String kSubjectGroupDesc = "SUBJ GROUP DESC";
	public static final String kHasSupplementalFiles = "HAS SUPP FILES";
	public static final String kSuppFileNames = "SUPPLEMENTAL FILE NAMES";
	public static final String kSuppFileDescription = "SUPPLEMENTAL FILE DESCRIPTION";
	public static final String kSuppFileCategory = "SUPPLEMENTAL FILE CATEGORY";
	public static final String kDepartmentName = "DEPARTMENT";
	public static final String kKeyword = "KEYWORD";
	public static final String kKeywordSource = "KEYWORD SOURCE";
	public static final String kSalesRestrictionCode = "SALES RESTRICTION CODE";
	public static final String kSalesRestrictionDesc = "SALES RESTRICTION DESC";
	public static final String kSalesRestrictionStartDate = "SALES RESTRICTION STARTDT";
	public static final String kSalesRestrictionEndDate = "SALES RESTRICTION ENDDT";
	public static final String kDissertationTypeCode = "DISS TYPE CODE";
	public static final String kDissertationCode = "DISS CODE";
	public static final String kDAISectionCode = "DAI SECTION CODE";
	public static final String kHasPDF = "PDF AVAILABLE";
	public static final String kPDFAvailableDate = "PDF AVAILABLE DATE";
	public static final String kFormatRestrictionCode = "FORMAT RESTRICTION CODE";
	public static final String kFormatRestrictionDesc = "FORMAT RESTRICTION DESC";
	public static final String kFormatRestrictionStartDt = "FORMAT RESTRICTION STARTDT";
	public static final String kFormatRestrictionEndDt = "FORMAT RESTRICTION ENDDT";
	public static final String kExternalId = "EXTERNAL ID";
	public static final String kOpenAccessFlag = "OPEN ACCESS";
	public static final String kAuthorCitizenship = "AUTHOR CITIZENSHIP";
	public static final String kPubDate = "PUB DATE";
	public static final String kManuscriptMediaCode = "MANUSCRIPTMEDIA CODE";
	public static final String kManuscriptMediaDesc = "MANUSCRIPTMEDIA DESC";
	public static final String kSchoolLocCountry = "LOC SCHOOL COUNTRY";
	public static final String kAuthorLocCitizenship = "LOC AUTHOR CITIZENSHIP";
	public static final String kDciRefsFlag = "DCI REFS";
	public static final String kCmteMember = "COMMITTEE MEMBERS";
	public static final String kActiveSalesRestrictionCode = "ACTIVE SALES RESTRICTION CODE";
	public static final String kActiveFormatRestrictionCode = "ACTIVE FORMAT RESTRICTION CODE";

}
