//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.16 at 11:24:47 AM EDT 
//


package com.proquest.mtg.dismetadataservice.mrngxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for degrees complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="degrees">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Degree" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DegreeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DegreeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DegreeYear" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sequence_number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "degrees", propOrder = {
    "degree"
})
public class Degrees {

    @XmlElement(name = "Degree", required = true)
    protected List<Degrees.Degree> degree;

    /**
     * Gets the value of the degree property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the degree property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDegree().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Degrees.Degree }
     * 
     * 
     */
    public List<Degrees.Degree> getDegree() {
        if (degree == null) {
            degree = new ArrayList<Degrees.Degree>();
        }
        return this.degree;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DegreeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DegreeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DegreeYear" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sequence_number" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "degreeCode",
        "degreeDescription",
        "degreeYear"
    })
    public static class Degree {

        @XmlElement(name = "DegreeCode", required = true)
        protected String degreeCode;
        @XmlElement(name = "DegreeDescription")
        protected String degreeDescription;
        @XmlElement(name = "DegreeYear")
        protected short degreeYear;
        @XmlAttribute(name = "sequence_number")
        protected Integer sequenceNumber;

        /**
         * Gets the value of the degreeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDegreeCode() {
            return degreeCode;
        }

        /**
         * Sets the value of the degreeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDegreeCode(String value) {
            this.degreeCode = value;
        }

        /**
         * Gets the value of the degreeDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDegreeDescription() {
            return degreeDescription;
        }

        /**
         * Sets the value of the degreeDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDegreeDescription(String value) {
            this.degreeDescription = value;
        }

        /**
         * Gets the value of the degreeYear property.
         * 
         */
        public short getDegreeYear() {
            return degreeYear;
        }

        /**
         * Sets the value of the degreeYear property.
         * 
         */
        public void setDegreeYear(short value) {
            this.degreeYear = value;
        }

        /**
         * Gets the value of the sequenceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSequenceNumber() {
            return sequenceNumber;
        }

        /**
         * Sets the value of the sequenceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSequenceNumber(Integer value) {
            this.sequenceNumber = value;
        }

    }

}
