//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 02:08:10 PM EST 
//


package com.proquest.mtg.dismetadataservice.mrngxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PubNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ISBN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PublisherNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Authors">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PrimaryAuthor" type="{}primaryAuthor"/>
 *                   &lt;element name="SecondaryAuthor" type="{}secondaryAuthor" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Batch">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DBTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DBTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="VolumeIssue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DAISectionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Title">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AlternateTitles" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AlternateTitle">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="School">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SchoolCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SchoolName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SchoolCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SchoolState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Departments" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Department" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Advisors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Advisor" type="{}advisor" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CmteMembers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CmteMember" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Keywords" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Keyword" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DissLanguage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Abstract" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AlternateAbstract" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pubNumber",
    "isbn",
    "publisherNote",
    "authors",
    "batch",
    "pageCount",
    "title",
    "alternateTitles",
    "school",
    "departments",
    "advisors",
    "cmteMembers",
    "keywords",
    "dissLanguage",
    "_abstract",
    "alternateAbstract"
})
@XmlRootElement(name = "Dissertation")
public class Dissertation {

    @XmlElement(name = "PubNumber", required = true)
    protected String pubNumber;
    @XmlElement(name = "ISBN")
    protected String isbn;
    @XmlElement(name = "PublisherNote")
    protected String publisherNote;
    @XmlElement(name = "Authors", required = true)
    protected Dissertation.Authors authors;
    @XmlElement(name = "Batch", required = true)
    protected Dissertation.Batch batch;
    @XmlElement(name = "PageCount")
    protected int pageCount;
    @XmlElement(name = "Title", required = true)
    protected Dissertation.Title title;
    @XmlElement(name = "AlternateTitles")
    protected Dissertation.AlternateTitles alternateTitles;
    @XmlElement(name = "School", required = true)
    protected Dissertation.School school;
    @XmlElement(name = "Departments")
    protected Dissertation.Departments departments;
    @XmlElement(name = "Advisors")
    protected Dissertation.Advisors advisors;
    @XmlElement(name = "CmteMembers")
    protected Dissertation.CmteMembers cmteMembers;
    @XmlElement(name = "Keywords")
    protected Dissertation.Keywords keywords;
    @XmlElement(name = "DissLanguage", required = true)
    protected String dissLanguage;
    @XmlElement(name = "Abstract")
    protected Dissertation.Abstract _abstract;
    @XmlElement(name = "AlternateAbstract")
    protected Dissertation.AlternateAbstract alternateAbstract;

    /**
     * Gets the value of the pubNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubNumber() {
        return pubNumber;
    }

    /**
     * Sets the value of the pubNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubNumber(String value) {
        this.pubNumber = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISBN() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISBN(String value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the publisherNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublisherNote() {
        return publisherNote;
    }

    /**
     * Sets the value of the publisherNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublisherNote(String value) {
        this.publisherNote = value;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.Authors }
     *     
     */
    public Dissertation.Authors getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.Authors }
     *     
     */
    public void setAuthors(Dissertation.Authors value) {
        this.authors = value;
    }

    /**
     * Gets the value of the batch property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.Batch }
     *     
     */
    public Dissertation.Batch getBatch() {
        return batch;
    }

    /**
     * Sets the value of the batch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.Batch }
     *     
     */
    public void setBatch(Dissertation.Batch value) {
        this.batch = value;
    }

    /**
     * Gets the value of the pageCount property.
     * 
     */
    public int getPageCount() {
        return pageCount;
    }

    /**
     * Sets the value of the pageCount property.
     * 
     */
    public void setPageCount(int value) {
        this.pageCount = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.Title }
     *     
     */
    public Dissertation.Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.Title }
     *     
     */
    public void setTitle(Dissertation.Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the alternateTitles property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.AlternateTitles }
     *     
     */
    public Dissertation.AlternateTitles getAlternateTitles() {
        return alternateTitles;
    }

    /**
     * Sets the value of the alternateTitles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.AlternateTitles }
     *     
     */
    public void setAlternateTitles(Dissertation.AlternateTitles value) {
        this.alternateTitles = value;
    }

    /**
     * Gets the value of the school property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.School }
     *     
     */
    public Dissertation.School getSchool() {
        return school;
    }

    /**
     * Sets the value of the school property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.School }
     *     
     */
    public void setSchool(Dissertation.School value) {
        this.school = value;
    }

    /**
     * Gets the value of the departments property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.Departments }
     *     
     */
    public Dissertation.Departments getDepartments() {
        return departments;
    }

    /**
     * Sets the value of the departments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.Departments }
     *     
     */
    public void setDepartments(Dissertation.Departments value) {
        this.departments = value;
    }

    /**
     * Gets the value of the advisors property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.Advisors }
     *     
     */
    public Dissertation.Advisors getAdvisors() {
        return advisors;
    }

    /**
     * Sets the value of the advisors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.Advisors }
     *     
     */
    public void setAdvisors(Dissertation.Advisors value) {
        this.advisors = value;
    }

    /**
     * Gets the value of the cmteMembers property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.CmteMembers }
     *     
     */
    public Dissertation.CmteMembers getCmteMembers() {
        return cmteMembers;
    }

    /**
     * Sets the value of the cmteMembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.CmteMembers }
     *     
     */
    public void setCmteMembers(Dissertation.CmteMembers value) {
        this.cmteMembers = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.Keywords }
     *     
     */
    public Dissertation.Keywords getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.Keywords }
     *     
     */
    public void setKeywords(Dissertation.Keywords value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the dissLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDissLanguage() {
        return dissLanguage;
    }

    /**
     * Sets the value of the dissLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDissLanguage(String value) {
        this.dissLanguage = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.Abstract }
     *     
     */
    public Dissertation.Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.Abstract }
     *     
     */
    public void setAbstract(Dissertation.Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the alternateAbstract property.
     * 
     * @return
     *     possible object is
     *     {@link Dissertation.AlternateAbstract }
     *     
     */
    public Dissertation.AlternateAbstract getAlternateAbstract() {
        return alternateAbstract;
    }

    /**
     * Sets the value of the alternateAbstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dissertation.AlternateAbstract }
     *     
     */
    public void setAlternateAbstract(Dissertation.AlternateAbstract value) {
        this.alternateAbstract = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Abstract {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Language")
        protected String language;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Advisor" type="{}advisor" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "advisor"
    })
    public static class Advisors {

        @XmlElement(name = "Advisor", required = true)
        protected List<Advisor> advisor;

        /**
         * Gets the value of the advisor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the advisor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdvisor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Advisor }
         * 
         * 
         */
        public List<Advisor> getAdvisor() {
            if (advisor == null) {
                advisor = new ArrayList<Advisor>();
            }
            return this.advisor;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AlternateAbstract {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Language")
        protected String language;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AlternateTitle">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "alternateTitle"
    })
    public static class AlternateTitles {

        @XmlElement(name = "AlternateTitle", required = true)
        protected Dissertation.AlternateTitles.AlternateTitle alternateTitle;

        /**
         * Gets the value of the alternateTitle property.
         * 
         * @return
         *     possible object is
         *     {@link Dissertation.AlternateTitles.AlternateTitle }
         *     
         */
        public Dissertation.AlternateTitles.AlternateTitle getAlternateTitle() {
            return alternateTitle;
        }

        /**
         * Sets the value of the alternateTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link Dissertation.AlternateTitles.AlternateTitle }
         *     
         */
        public void setAlternateTitle(Dissertation.AlternateTitles.AlternateTitle value) {
            this.alternateTitle = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class AlternateTitle {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Language")
            protected String language;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the language property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLanguage() {
                return language;
            }

            /**
             * Sets the value of the language property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLanguage(String value) {
                this.language = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PrimaryAuthor" type="{}primaryAuthor"/>
     *         &lt;element name="SecondaryAuthor" type="{}secondaryAuthor" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "primaryAuthor",
        "secondaryAuthor"
    })
    public static class Authors {

        @XmlElement(name = "PrimaryAuthor", required = true)
        protected PrimaryAuthor primaryAuthor;
        @XmlElement(name = "SecondaryAuthor")
        protected List<SecondaryAuthor> secondaryAuthor;

        /**
         * Gets the value of the primaryAuthor property.
         * 
         * @return
         *     possible object is
         *     {@link PrimaryAuthor }
         *     
         */
        public PrimaryAuthor getPrimaryAuthor() {
            return primaryAuthor;
        }

        /**
         * Sets the value of the primaryAuthor property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrimaryAuthor }
         *     
         */
        public void setPrimaryAuthor(PrimaryAuthor value) {
            this.primaryAuthor = value;
        }

        /**
         * Gets the value of the secondaryAuthor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the secondaryAuthor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSecondaryAuthor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SecondaryAuthor }
         * 
         * 
         */
        public List<SecondaryAuthor> getSecondaryAuthor() {
            if (secondaryAuthor == null) {
                secondaryAuthor = new ArrayList<SecondaryAuthor>();
            }
            return this.secondaryAuthor;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DBTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DBTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="VolumeIssue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DAISectionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dbTypeCode",
        "dbTypeDesc",
        "volumeIssue",
        "daiSectionCode"
    })
    public static class Batch {

        @XmlElement(name = "DBTypeCode")
        protected String dbTypeCode;
        @XmlElement(name = "DBTypeDesc")
        protected String dbTypeDesc;
        @XmlElement(name = "VolumeIssue")
        protected String volumeIssue;
        @XmlElement(name = "DAISectionCode")
        protected String daiSectionCode;

        /**
         * Gets the value of the dbTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDBTypeCode() {
            return dbTypeCode;
        }

        /**
         * Sets the value of the dbTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDBTypeCode(String value) {
            this.dbTypeCode = value;
        }

        /**
         * Gets the value of the dbTypeDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDBTypeDesc() {
            return dbTypeDesc;
        }

        /**
         * Sets the value of the dbTypeDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDBTypeDesc(String value) {
            this.dbTypeDesc = value;
        }

        /**
         * Gets the value of the volumeIssue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVolumeIssue() {
            return volumeIssue;
        }

        /**
         * Sets the value of the volumeIssue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVolumeIssue(String value) {
            this.volumeIssue = value;
        }

        /**
         * Gets the value of the daiSectionCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDAISectionCode() {
            return daiSectionCode;
        }

        /**
         * Sets the value of the daiSectionCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDAISectionCode(String value) {
            this.daiSectionCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CmteMember" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cmteMember"
    })
    public static class CmteMembers {

        @XmlElement(name = "CmteMember")
        protected List<Dissertation.CmteMembers.CmteMember> cmteMember;

        /**
         * Gets the value of the cmteMember property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cmteMember property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCmteMember().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dissertation.CmteMembers.CmteMember }
         * 
         * 
         */
        public List<Dissertation.CmteMembers.CmteMember> getCmteMember() {
            if (cmteMember == null) {
                cmteMember = new ArrayList<Dissertation.CmteMembers.CmteMember>();
            }
            return this.cmteMember;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "firstName",
            "middleName",
            "lastName",
            "suffix"
        })
        public static class CmteMember {

            @XmlElement(name = "FirstName", required = true)
            protected String firstName;
            @XmlElement(name = "MiddleName")
            protected String middleName;
            @XmlElement(name = "LastName", required = true)
            protected String lastName;
            @XmlElement(name = "Suffix")
            protected String suffix;

            /**
             * Gets the value of the firstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFirstName() {
                return firstName;
            }

            /**
             * Sets the value of the firstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFirstName(String value) {
                this.firstName = value;
            }

            /**
             * Gets the value of the middleName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMiddleName() {
                return middleName;
            }

            /**
             * Sets the value of the middleName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMiddleName(String value) {
                this.middleName = value;
            }

            /**
             * Gets the value of the lastName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLastName() {
                return lastName;
            }

            /**
             * Sets the value of the lastName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLastName(String value) {
                this.lastName = value;
            }

            /**
             * Gets the value of the suffix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSuffix() {
                return suffix;
            }

            /**
             * Sets the value of the suffix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSuffix(String value) {
                this.suffix = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Department" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "department"
    })
    public static class Departments {

        @XmlElement(name = "Department", required = true)
        protected List<String> department;

        /**
         * Gets the value of the department property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the department property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDepartment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDepartment() {
            if (department == null) {
                department = new ArrayList<String>();
            }
            return this.department;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Keyword" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Source" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "keyword"
    })
    public static class Keywords {

        @XmlElement(name = "Keyword", required = true)
        protected List<Dissertation.Keywords.Keyword> keyword;

        /**
         * Gets the value of the keyword property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the keyword property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKeyword().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dissertation.Keywords.Keyword }
         * 
         * 
         */
        public List<Dissertation.Keywords.Keyword> getKeyword() {
            if (keyword == null) {
                keyword = new ArrayList<Dissertation.Keywords.Keyword>();
            }
            return this.keyword;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Source" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Keyword {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Source")
            protected String source;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSource() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSource(String value) {
                this.source = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SchoolCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SchoolName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SchoolCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SchoolState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "schoolCode",
        "schoolName",
        "schoolCountry",
        "schoolState"
    })
    public static class School {

        @XmlElement(name = "SchoolCode", required = true)
        protected String schoolCode;
        @XmlElement(name = "SchoolName", required = true)
        protected String schoolName;
        @XmlElement(name = "SchoolCountry", required = true)
        protected String schoolCountry;
        @XmlElement(name = "SchoolState")
        protected String schoolState;

        /**
         * Gets the value of the schoolCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSchoolCode() {
            return schoolCode;
        }

        /**
         * Sets the value of the schoolCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSchoolCode(String value) {
            this.schoolCode = value;
        }

        /**
         * Gets the value of the schoolName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSchoolName() {
            return schoolName;
        }

        /**
         * Sets the value of the schoolName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSchoolName(String value) {
            this.schoolName = value;
        }

        /**
         * Gets the value of the schoolCountry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSchoolCountry() {
            return schoolCountry;
        }

        /**
         * Sets the value of the schoolCountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSchoolCountry(String value) {
            this.schoolCountry = value;
        }

        /**
         * Gets the value of the schoolState property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSchoolState() {
            return schoolState;
        }

        /**
         * Sets the value of the schoolState property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSchoolState(String value) {
            this.schoolState = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Language" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Title {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Language")
        protected String language;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

    }

}
