//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.16 at 02:01:28 PM EDT 
//


package com.proquest.mtg.dismetadataservice.mrngxml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.proquest.mtg.dismetadataservice.mrngxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.proquest.mtg.dismetadataservice.mrngxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dissertation }
     * 
     */
    public Dissertation createDissertation() {
        return new Dissertation();
    }

    /**
     * Create an instance of {@link Degrees }
     * 
     */
    public Degrees createDegrees() {
        return new Degrees();
    }

    /**
     * Create an instance of {@link PrimaryAuthor }
     * 
     */
    public PrimaryAuthor createPrimaryAuthor() {
        return new PrimaryAuthor();
    }

    /**
     * Create an instance of {@link SecondaryAuthor }
     * 
     */
    public SecondaryAuthor createSecondaryAuthor() {
        return new SecondaryAuthor();
    }

    /**
     * Create an instance of {@link Dissertation.Keywords }
     * 
     */
    public Dissertation.Keywords createDissertationKeywords() {
        return new Dissertation.Keywords();
    }

    /**
     * Create an instance of {@link Dissertation.CmteMembers }
     * 
     */
    public Dissertation.CmteMembers createDissertationCmteMembers() {
        return new Dissertation.CmteMembers();
    }

    /**
     * Create an instance of {@link Dissertation.Advisors }
     * 
     */
    public Dissertation.Advisors createDissertationAdvisors() {
        return new Dissertation.Advisors();
    }

    /**
     * Create an instance of {@link Dissertation.Advisors.Advisor }
     * 
     */
    public Dissertation.Advisors.Advisor createDissertationAdvisorsAdvisor() {
        return new Dissertation.Advisors.Advisor();
    }

    /**
     * Create an instance of {@link Dissertation.AlternateTitles }
     * 
     */
    public Dissertation.AlternateTitles createDissertationAlternateTitles() {
        return new Dissertation.AlternateTitles();
    }

    /**
     * Create an instance of {@link Dissertation.Authors }
     * 
     */
    public Dissertation.Authors createDissertationAuthors() {
        return new Dissertation.Authors();
    }

    /**
     * Create an instance of {@link Dissertation.Batch }
     * 
     */
    public Dissertation.Batch createDissertationBatch() {
        return new Dissertation.Batch();
    }

    /**
     * Create an instance of {@link Dissertation.Title }
     * 
     */
    public Dissertation.Title createDissertationTitle() {
        return new Dissertation.Title();
    }

    /**
     * Create an instance of {@link Dissertation.School }
     * 
     */
    public Dissertation.School createDissertationSchool() {
        return new Dissertation.School();
    }

    /**
     * Create an instance of {@link Dissertation.Departments }
     * 
     */
    public Dissertation.Departments createDissertationDepartments() {
        return new Dissertation.Departments();
    }

    /**
     * Create an instance of {@link Dissertation.Abstract }
     * 
     */
    public Dissertation.Abstract createDissertationAbstract() {
        return new Dissertation.Abstract();
    }

    /**
     * Create an instance of {@link Dissertation.AlternateAbstract }
     * 
     */
    public Dissertation.AlternateAbstract createDissertationAlternateAbstract() {
        return new Dissertation.AlternateAbstract();
    }

    /**
     * Create an instance of {@link Degrees.Degree }
     * 
     */
    public Degrees.Degree createDegreesDegree() {
        return new Degrees.Degree();
    }

    /**
     * Create an instance of {@link PrimaryAuthor.AltAuthorFullName }
     * 
     */
    public PrimaryAuthor.AltAuthorFullName createPrimaryAuthorAltAuthorFullName() {
        return new PrimaryAuthor.AltAuthorFullName();
    }

    /**
     * Create an instance of {@link SecondaryAuthor.AltAuthorFullName }
     * 
     */
    public SecondaryAuthor.AltAuthorFullName createSecondaryAuthorAltAuthorFullName() {
        return new SecondaryAuthor.AltAuthorFullName();
    }

    /**
     * Create an instance of {@link Dissertation.Keywords.Keyword }
     * 
     */
    public Dissertation.Keywords.Keyword createDissertationKeywordsKeyword() {
        return new Dissertation.Keywords.Keyword();
    }

    /**
     * Create an instance of {@link Dissertation.CmteMembers.CmteMember }
     * 
     */
    public Dissertation.CmteMembers.CmteMember createDissertationCmteMembersCmteMember() {
        return new Dissertation.CmteMembers.CmteMember();
    }

    /**
     * Create an instance of {@link Dissertation.Advisors.Advisor.AltAdvisorFullName }
     * 
     */
    public Dissertation.Advisors.Advisor.AltAdvisorFullName createDissertationAdvisorsAdvisorAltAdvisorFullName() {
        return new Dissertation.Advisors.Advisor.AltAdvisorFullName();
    }

    /**
     * Create an instance of {@link Dissertation.AlternateTitles.AlternateTitle }
     * 
     */
    public Dissertation.AlternateTitles.AlternateTitle createDissertationAlternateTitlesAlternateTitle() {
        return new Dissertation.AlternateTitles.AlternateTitle();
    }

}
