//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.13 at 12:02:58 PM EDT 
//


package com.proquest.mtg.dismetadataservice.pqloc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Certification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Certification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CertificationAuthority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CertifiedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ApplicantInternalTrackingNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Certification", propOrder = {
    "certificationAuthority",
    "certifiedBy",
    "comments",
    "applicantInternalTrackingNumber"
})
public class Certification {

    @XmlElement(name = "CertificationAuthority", required = true)
    protected String certificationAuthority;
    @XmlElement(name = "CertifiedBy", required = true)
    protected String certifiedBy;
    @XmlElement(name = "Comments")
    protected String comments;
    @XmlElement(name = "ApplicantInternalTrackingNumber")
    protected String applicantInternalTrackingNumber;

    /**
     * Gets the value of the certificationAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationAuthority() {
        return certificationAuthority;
    }

    /**
     * Sets the value of the certificationAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationAuthority(String value) {
        this.certificationAuthority = value;
    }

    /**
     * Gets the value of the certifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertifiedBy() {
        return certifiedBy;
    }

    /**
     * Sets the value of the certifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertifiedBy(String value) {
        this.certifiedBy = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the applicantInternalTrackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicantInternalTrackingNumber() {
        return applicantInternalTrackingNumber;
    }

    /**
     * Sets the value of the applicantInternalTrackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicantInternalTrackingNumber(String value) {
        this.applicantInternalTrackingNumber = value;
    }

}
