//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.27 at 12:17:30 PM EDT 
//


package com.proquest.mtg.dismetadataservice.externalurl.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dissertation" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PubID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ExtURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dissertation"
})
@XmlRootElement(name = "DissertationList")
public class DissertationList {

    @XmlElement(name = "Dissertation", required = true)
    protected List<DissertationList.Dissertation> dissertation;

    /**
     * Gets the value of the dissertation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dissertation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDissertation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DissertationList.Dissertation }
     * 
     * 
     */
    public List<DissertationList.Dissertation> getDissertation() {
        if (dissertation == null) {
            dissertation = new ArrayList<DissertationList.Dissertation>();
        }
        return this.dissertation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PubID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ExtURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pubID",
        "extURL"
    })
    public static class Dissertation {

        @XmlElement(name = "PubID", required = true)
        protected String pubID;
        @XmlElement(name = "ExtURL", required = true)
        protected String extURL;

        /**
         * Gets the value of the pubID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPubID() {
            return pubID;
        }

        /**
         * Sets the value of the pubID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPubID(String value) {
            this.pubID = value;
        }

        /**
         * Gets the value of the extURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtURL() {
            return extURL;
        }

        /**
         * Sets the value of the extURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtURL(String value) {
            this.extURL = value;
        }

    }

}
