//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.13 at 12:02:58 PM EDT 
//


package com.proquest.mtg.dismetadataservice.pqloc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Claim" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SRNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CustomerClaimId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TypeofWork" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Publication">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="YearofCompletion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PreregistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="PublishedWork" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NationofFirstPublication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DateOffirstpublication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="StandardWorkIdentifierValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="StandardWorkIdentifierType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Titles" type="{}Titles"/>
 *                             &lt;element name="Authors" type="{}Authors"/>
 *                             &lt;element name="Claimants" type="{}Claimants"/>
 *                             &lt;element name="LimitationOfClaim" type="{}LimitationOfClaim"/>
 *                             &lt;element name="CertificateMailingAddresses" type="{}CertificateMailingAddresses"/>
 *                             &lt;element name="Certification" type="{}Certification"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "claim"
})
@XmlRootElement(name = "Claims")
public class Claims {

    @XmlElement(name = "Claim", required = true)
    protected List<Claims.Claim> claim;

    /**
     * Gets the value of the claim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the claim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClaim().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Claims.Claim }
     * 
     * 
     */
    public List<Claims.Claim> getClaim() {
        if (claim == null) {
            claim = new ArrayList<Claims.Claim>();
        }
        return this.claim;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SRNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CustomerClaimId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TypeofWork" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Publication">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="YearofCompletion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PreregistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="PublishedWork" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NationofFirstPublication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DateOffirstpublication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="StandardWorkIdentifierValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="StandardWorkIdentifierType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Titles" type="{}Titles"/>
     *                   &lt;element name="Authors" type="{}Authors"/>
     *                   &lt;element name="Claimants" type="{}Claimants"/>
     *                   &lt;element name="LimitationOfClaim" type="{}LimitationOfClaim"/>
     *                   &lt;element name="CertificateMailingAddresses" type="{}CertificateMailingAddresses"/>
     *                   &lt;element name="Certification" type="{}Certification"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "srNumber",
        "customerClaimId",
        "typeofWork",
        "publication"
    })
    public static class Claim {

        @XmlElement(name = "SRNumber", required = true)
        protected String srNumber;
        @XmlElement(name = "CustomerClaimId", required = true)
        protected String customerClaimId;
        @XmlElement(name = "TypeofWork", required = true)
        protected String typeofWork;
        @XmlElement(name = "Publication", required = true)
        protected Claims.Claim.Publication publication;

        /**
         * Gets the value of the srNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSRNumber() {
            return srNumber;
        }

        /**
         * Sets the value of the srNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSRNumber(String value) {
            this.srNumber = value;
        }

        /**
         * Gets the value of the customerClaimId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerClaimId() {
            return customerClaimId;
        }

        /**
         * Sets the value of the customerClaimId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerClaimId(String value) {
            this.customerClaimId = value;
        }

        /**
         * Gets the value of the typeofWork property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeofWork() {
            return typeofWork;
        }

        /**
         * Sets the value of the typeofWork property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeofWork(String value) {
            this.typeofWork = value;
        }

        /**
         * Gets the value of the publication property.
         * 
         * @return
         *     possible object is
         *     {@link Claims.Claim.Publication }
         *     
         */
        public Claims.Claim.Publication getPublication() {
            return publication;
        }

        /**
         * Sets the value of the publication property.
         * 
         * @param value
         *     allowed object is
         *     {@link Claims.Claim.Publication }
         *     
         */
        public void setPublication(Claims.Claim.Publication value) {
            this.publication = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="YearofCompletion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PreregistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="PublishedWork" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="NationofFirstPublication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DateOffirstpublication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="StandardWorkIdentifierValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="StandardWorkIdentifierType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Titles" type="{}Titles"/>
         *         &lt;element name="Authors" type="{}Authors"/>
         *         &lt;element name="Claimants" type="{}Claimants"/>
         *         &lt;element name="LimitationOfClaim" type="{}LimitationOfClaim"/>
         *         &lt;element name="CertificateMailingAddresses" type="{}CertificateMailingAddresses"/>
         *         &lt;element name="Certification" type="{}Certification"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "yearofCompletion",
            "preregistrationNumber",
            "publishedWork",
            "nationofFirstPublication",
            "dateOffirstpublication",
            "standardWorkIdentifierValue",
            "standardWorkIdentifierType",
            "titles",
            "authors",
            "claimants",
            "limitationOfClaim",
            "certificateMailingAddresses",
            "certification"
        })
        public static class Publication {

            @XmlElement(name = "YearofCompletion", required = true)
            protected String yearofCompletion;
            @XmlElement(name = "PreregistrationNumber")
            protected String preregistrationNumber;
            @XmlElement(name = "PublishedWork", required = true)
            protected String publishedWork;
            @XmlElement(name = "NationofFirstPublication")
            protected String nationofFirstPublication;
            @XmlElement(name = "DateOffirstpublication")
            protected String dateOffirstpublication;
            @XmlElement(name = "StandardWorkIdentifierValue")
            protected String standardWorkIdentifierValue;
            @XmlElement(name = "StandardWorkIdentifierType")
            protected String standardWorkIdentifierType;
            @XmlElement(name = "Titles", required = true)
            protected Titles titles;
            @XmlElement(name = "Authors", required = true)
            protected Authors authors;
            @XmlElement(name = "Claimants", required = true)
            protected Claimants claimants;
            @XmlElement(name = "LimitationOfClaim", required = true)
            protected LimitationOfClaim limitationOfClaim;
            @XmlElement(name = "CertificateMailingAddresses", required = true)
            protected CertificateMailingAddresses certificateMailingAddresses;
            @XmlElement(name = "Certification", required = true)
            protected Certification certification;

            /**
             * Gets the value of the yearofCompletion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getYearofCompletion() {
                return yearofCompletion;
            }

            /**
             * Sets the value of the yearofCompletion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setYearofCompletion(String value) {
                this.yearofCompletion = value;
            }

            /**
             * Gets the value of the preregistrationNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPreregistrationNumber() {
                return preregistrationNumber;
            }

            /**
             * Sets the value of the preregistrationNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPreregistrationNumber(String value) {
                this.preregistrationNumber = value;
            }

            /**
             * Gets the value of the publishedWork property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPublishedWork() {
                return publishedWork;
            }

            /**
             * Sets the value of the publishedWork property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPublishedWork(String value) {
                this.publishedWork = value;
            }

            /**
             * Gets the value of the nationofFirstPublication property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNationofFirstPublication() {
                return nationofFirstPublication;
            }

            /**
             * Sets the value of the nationofFirstPublication property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNationofFirstPublication(String value) {
                this.nationofFirstPublication = value;
            }

            /**
             * Gets the value of the dateOffirstpublication property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateOffirstpublication() {
                return dateOffirstpublication;
            }

            /**
             * Sets the value of the dateOffirstpublication property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateOffirstpublication(String value) {
                this.dateOffirstpublication = value;
            }

            /**
             * Gets the value of the standardWorkIdentifierValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStandardWorkIdentifierValue() {
                return standardWorkIdentifierValue;
            }

            /**
             * Sets the value of the standardWorkIdentifierValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStandardWorkIdentifierValue(String value) {
                this.standardWorkIdentifierValue = value;
            }

            /**
             * Gets the value of the standardWorkIdentifierType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStandardWorkIdentifierType() {
                return standardWorkIdentifierType;
            }

            /**
             * Sets the value of the standardWorkIdentifierType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStandardWorkIdentifierType(String value) {
                this.standardWorkIdentifierType = value;
            }

            /**
             * Gets the value of the titles property.
             * 
             * @return
             *     possible object is
             *     {@link Titles }
             *     
             */
            public Titles getTitles() {
                return titles;
            }

            /**
             * Sets the value of the titles property.
             * 
             * @param value
             *     allowed object is
             *     {@link Titles }
             *     
             */
            public void setTitles(Titles value) {
                this.titles = value;
            }

            /**
             * Gets the value of the authors property.
             * 
             * @return
             *     possible object is
             *     {@link Authors }
             *     
             */
            public Authors getAuthors() {
                return authors;
            }

            /**
             * Sets the value of the authors property.
             * 
             * @param value
             *     allowed object is
             *     {@link Authors }
             *     
             */
            public void setAuthors(Authors value) {
                this.authors = value;
            }

            /**
             * Gets the value of the claimants property.
             * 
             * @return
             *     possible object is
             *     {@link Claimants }
             *     
             */
            public Claimants getClaimants() {
                return claimants;
            }

            /**
             * Sets the value of the claimants property.
             * 
             * @param value
             *     allowed object is
             *     {@link Claimants }
             *     
             */
            public void setClaimants(Claimants value) {
                this.claimants = value;
            }

            /**
             * Gets the value of the limitationOfClaim property.
             * 
             * @return
             *     possible object is
             *     {@link LimitationOfClaim }
             *     
             */
            public LimitationOfClaim getLimitationOfClaim() {
                return limitationOfClaim;
            }

            /**
             * Sets the value of the limitationOfClaim property.
             * 
             * @param value
             *     allowed object is
             *     {@link LimitationOfClaim }
             *     
             */
            public void setLimitationOfClaim(LimitationOfClaim value) {
                this.limitationOfClaim = value;
            }

            /**
             * Gets the value of the certificateMailingAddresses property.
             * 
             * @return
             *     possible object is
             *     {@link CertificateMailingAddresses }
             *     
             */
            public CertificateMailingAddresses getCertificateMailingAddresses() {
                return certificateMailingAddresses;
            }

            /**
             * Sets the value of the certificateMailingAddresses property.
             * 
             * @param value
             *     allowed object is
             *     {@link CertificateMailingAddresses }
             *     
             */
            public void setCertificateMailingAddresses(CertificateMailingAddresses value) {
                this.certificateMailingAddresses = value;
            }

            /**
             * Gets the value of the certification property.
             * 
             * @return
             *     possible object is
             *     {@link Certification }
             *     
             */
            public Certification getCertification() {
                return certification;
            }

            /**
             * Sets the value of the certification property.
             * 
             * @param value
             *     allowed object is
             *     {@link Certification }
             *     
             */
            public void setCertification(Certification value) {
                this.certification = value;
            }

        }

    }

}
